# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6ede306a7b00bc486376460b4ffdb3eb367bef1c4b3c0cdb7888bcb9aeb3f46042f4ae614b0ba6fc5f896477e8c7be753c947b573a260b8d6c735a7b48e89c

test:
  secret_key_base: e09f8979ecf231252817c75ddda0a76ec1ce46b0d7f3e4d484421e6076722fe123577c9ad3c62336c1f9a0a2d8b45879c96dcff1e4e7b6873c6a7a488680008f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
